name:                RoomBooker
version:             0.1.0.0
github:              "githubuser/RoomBooker"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/RoomBooker#readme>

dependencies:
- base >= 4.7 && < 5
- telegram-bot-simple
- telegram-bot-api # == 6.7
- http-client
- http-client-tls
- text
- time
- bytestring
- mtl
- transformers
# - postgresql-simple
# - postgresql-simple-migration
- dotenv
- data-has
- record-hasfield
- either
- exceptions
- resource-pool
- unliftio
- unordered-containers

default-extensions:
- OverloadedStrings
- QuasiQuotes
- NamedFieldPuns

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  RoomBooker-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - RoomBooker

